USE `hoangbao_cosmetics_db`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ==========================================
-- BẢNG BLOG / BÀI VIẾT & CẨM NANG HOẠT CHẤT (TỪ DỮ LIỆU ĐÃ GỬI)
-- ==========================================
CREATE TABLE IF NOT EXISTS `blog_categories` (
  `id_category` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `blog_authors` (
  `id_author` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL,
  `department` varchar(255) DEFAULT NULL,
  `avatar` varchar(500) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  PRIMARY KEY (`id_author`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `articles` (
  `id_article` varchar(100) NOT NULL,
  `title` varchar(500) NOT NULL,
  `subtitle` text DEFAULT NULL,
  `id_category` varchar(50) NOT NULL,
  `id_author` varchar(50) NOT NULL,
  `published_date` varchar(50) DEFAULT NULL,
  `time_published` varchar(20) DEFAULT NULL,
  `read_time` varchar(50) DEFAULT NULL,
  `views` int(11) DEFAULT 0,
  `thumbnail` varchar(500) DEFAULT NULL,
  `photo_credit` varchar(255) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `pull_quote` text DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `content_intro` text DEFAULT NULL,
  `content_conclusion` text DEFAULT NULL,
  `recommended_products` text DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_article`),
  FOREIGN KEY (`id_category`) REFERENCES `blog_categories` (`id_category`),
  FOREIGN KEY (`id_author`) REFERENCES `blog_authors` (`id_author`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `ingredient_guides` (
  `id_guide` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `scientific_name` varchar(255) NOT NULL,
  `role` text NOT NULL,
  `suitable_for` text NOT NULL,
  `note` text DEFAULT NULL,
  `dosage` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_guide`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
-- 1. INSERT BLOG CATEGORIES
INSERT INTO `blog_categories` (`id_category`, `name`) VALUES ('skincare', 'Khoa học Chăm sóc da') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_categories` (`id_category`, `name`) VALUES ('treatment', 'Phục hồi & Trị liệu Da liễu') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_categories` (`id_category`, `name`) VALUES ('ingredients', 'Cẩm nang Hoạt chất Y khoa') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_categories` (`id_category`, `name`) VALUES ('makeup', 'Nghệ thuật Trang điểm') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_categories` (`id_category`, `name`) VALUES ('trends', 'Xu hướng & Phong cách sống') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- 2. INSERT BLOG AUTHORS
INSERT INTO `blog_authors` (`id_author`, `name`, `role`, `department`, `avatar`, `bio`) VALUES ('dr_lan_anh', 'BS. CKII Nguyễn Lan Anh', 'Bác sĩ Chuyên khoa II Da liễu - Cố vấn Y khoa Hoàng Bảo', 'Hội đồng Da liễu Lâm sàng & Thẩm mỹ TP.HCM', 'https://images.unsplash.com/photo-1594824813629-87cfa77d0186?w=400&q=80&auto=format&fit=crop', 'Bác sĩ Lan Anh có hơn 14 năm kinh nghiệm công tác tại các bệnh viện da liễu tuyến đầu, chuyên nghiên cứu về sinh lý học màng lipid biểu bì và phục hồi da tổn thương sau can thiệp thẩm mỹ.') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_authors` (`id_author`, `name`, `role`, `department`, `avatar`, `bio`) VALUES ('mai_phuong', 'Nhà báo Mai Phương', 'Trưởng ban Biên tập Khoa học Làn da & Mỹ phẩm', 'Tạp chí Hoàng Bảo Beauty Journal', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80&auto=format&fit=crop', 'Tốt nghiệp cử nhân Hóa dược Đại học Quốc gia, Mai Phương đã có 9 năm theo đuổi mảng báo chí phân tích hoạt chất mỹ phẩm và phỏng vấn các chuyên gia đầu ngành trong và ngoài nước.') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `blog_authors` (`id_author`, `name`, `role`, `department`, `avatar`, `bio`) VALUES ('hoang_nam', 'Chuyên gia Hoàng Nam', 'Giám đốc Nghệ thuật & Chuyên gia Trang điểm Cao cấp', 'Ban Đào tạo Nghệ thuật Trang điểm Chuyên nghiệp', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80&auto=format&fit=crop', 'Từng tu nghiệp tại Paris và Seoul, Hoàng Nam sở hữu hơn 10 năm kinh nghiệm định hình phong cách trang điểm cho các tuần lễ thời trang và cố vấn sắc tố da cho người phụ nữ Á Đông.') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- 3. INSERT ARTICLES
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('skincare-routine-beginner', 'Giải mã quy trình 7 bước dưỡng da chuẩn da liễu: Cơ chế thẩm thấu và nguyên lý phục hồi màng lipid', 'Nhiều người chi hàng chục triệu đồng cho serum cao cấp nhưng làn da vẫn sần sùi bít tắc. Bản báo cáo chuyên sâu này sẽ phân tích tường tận nguyên lý hấp thu tế bào và thứ tự chăm sóc khoa học.', 'skincare', 'dr_lan_anh', '15/09/2026', '08:30', '8 phút đọc', 4820, 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=1400&q=85&auto=format&fit=crop', 'Getty Images / Tư liệu nghiên cứu Viện Da liễu Quốc tế', 'Phân tích cơ chế sinh học đằng sau kỹ thuật Double Cleansing, nguyên lý ngậm nước đa tầng của Hyaluronic Acid và vai trò tối thượng của việc củng cố lớp màng Ceramide bảo vệ da.', '{"quote": "Làn da không phải là một chiếc xô để chúng ta đổ dồn dập mọi hoạt chất đắt tiền vào. Nó là một cơ quan sống với hệ sinh thái vi sinh vật và cấu trúc biểu mô đa tầng đòi hỏi sự tôn trọng nhịp sinh học tự nhiên.", "speaker": "BS. CKII Nguyễn Lan Anh (Cố vấn Y khoa Hoàng Bảo)"}', '["Sinh lý da", "Skincare Routine", "Làm sạch kép", "Hàng rào lipid", "Da liễu học"]', 'Theo thống kê lâm sàng tại các phòng khám da liễu lớn năm 2025, có tới hơn 68% trường hợp bệnh nhân gặp tình trạng viêm da tiếp xúc hoặc bùng phát mụn ẩn không phải do thiếu mỹ phẩm, mà do sử dụng quá nhiều sản phẩm sai thứ tự và triệt tiêu màng ẩm sinh học của cơ thể. Để các phân tử dưỡng chất có thể xuyên qua lớp sừng dày từ 15-20 lớp tế bào dẹt, quy trình chăm sóc cần được thiết kế dựa trên định luật khuếch tán Fick và độ phân cực của từng nhóm dung môi.', 'Chăm sóc da khoa học là sự hòa hợp giữa kiến thức sinh lý và tính kỷ luật đều đặn mỗi ngày. Khi bạn từ bỏ thói quen bôi thoa theo trào lưu thiếu căn cứ và bắt đầu lắng nghe phản ứng sinh học của làn da, bạn sẽ nhận thấy sự biến chuyển ngoạn mục: lỗ chân lông se khít tự nhiên, độ đàn hồi gia tăng và làn da toát lên vẻ căng bóng khỏe mạnh từ sâu bên trong.', '[{"name": "Nước Hoa Hồng Cân Bằng Cấp Ẩm Chuyên Sâu Hoàng Bảo", "category": "Toner Dược Liệu", "price": 350000}, {"name": "Tinh Chất Phục Hồi Dịu Da B5 & Rau Má Tinh Khiết", "category": "Serum Chuyên Sâu", "price": 450000}, {"name": "Kem Dưỡng Sinh Học Phục Hồi Màng Lipid Ceramide Complex", "category": "Kem Dưỡng Khóa Ẩm", "price": 390000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('sunscreen-common-mistakes', 'Nghiên cứu lâm sàng về 5 sai lầm khi thoa kem chống nắng: Vì sao chỉ số SPF trên nhãn chai không phát huy tác dụng?', 'Tại sao bạn bôi kem chống nắng đều đặn mỗi sáng nhưng vết nám và đốm nâu vẫn xuất hiện sau tuổi 25? Chuyên gia quang sinh học bóc tách các sai số phổ biến trong thói quen bảo vệ da.', 'skincare', 'mai_phuong', '12/09/2026', '14:15', '7 phút đọc', 4190, 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=1400&q=85&auto=format&fit=crop', 'Phòng Thí nghiệm Quang sinh học & Thử nghiệm SPF Lâm sàng', 'Phân tích định lượng liều dùng 2mg/cm², hiện tượng phân rã màng lọc quang phổ rộng dưới nhiệt lượng và giải pháp dặm lại kem chống nắng cho người trang điểm.', '{"quote": "Kem chống nắng không phải là áo giáp bất khả xâm phạm. Nếu bôi sai liều lượng hoặc quên dặm lại, bạn đang tạo ra một ảo tưởng an toàn nguy hiểm cho các tế bào biểu bì bên dưới.", "speaker": "Nhà báo Mai Phương (Trưởng ban Khoa học Làn da)"}', '["Kem chống nắng", "Tia UVA/UVB", "Quang hóa học", "Sạm nám da", "Bảo vệ da"]', 'Bức xạ tử ngoại mặt trời gồm tia UVB (bước sóng 290-320nm gây bỏng rát, đỏ da) và tia UVA (bước sóng 320-400nm len lỏi sâu vào hạ bì, phá vỡ cấu trúc collagen và làm đứt gãy sợi elastin). Hơn 95% lượng tia UV chạm tới mặt đất là tia UVA, loại bức xạ có khả năng xuyên qua mây mù, sương sớm và cả kính cửa sổ văn phòng. Dù bạn ở trong phòng máy lạnh cả ngày, làn da vẫn đang âm thầm bị tổn thương DNA nếu không được bảo vệ đúng cách.', 'Kem chống nắng không chỉ là một sản phẩm làm đẹp đơn thuần, mà là phương pháp y tế dự phòng hiệu quả và kinh tế nhất chống lại sự suy thoái ADN tế bào và ung thư biểu mô da. Hãy xây dựng thói quen thoa đủ liều lượng và dặm lại như một nguyên tắc bất biến để bảo vệ làn da thanh xuân qua năm tháng.', '[{"name": "Kem Chống Nắng Vật Lý Lai Hóa Học SPF50+ PA++++ Kiềm Dầu", "category": "Chống Nắng Y Khoa", "price": 420000}, {"name": "Xịt Khoáng Chống Nắng Bảo Vệ Phổ Rộng Dặm Nhanh", "category": "Chống Nắng Tiện Lợi", "price": 295000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('bha-aha-niacinamide-guide', 'Bách khoa toàn thư hoạt chất: So sánh cơ chế sinh hóa giữa AHA, BHA và Niacinamide trong điều trị mụn và thu nhỏ lỗ chân lông', 'Nồng độ bao nhiêu là an toàn cho da người Việt? Cách kết hợp bộ ba hoạt chất vàng để triệt tiêu sợi bã nhờn mà không phá hủy hàng rào bảo vệ da.', 'ingredients', 'dr_lan_anh', '10/09/2026', '09:45', '9 phút đọc', 5320, 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=1400&q=85&auto=format&fit=crop', 'Viện Kiểm nghiệm Dược phẩm & Hóa mỹ phẩm Trung ương', 'Bản phân tích chuyên sâu phân tử lượng, tính tan trong nước và lipid của Glycolic Acid, Salicylic Acid và dẫn xuất Nicotinamide trong phác đồ da liễu.', '{"quote": "Làn da của người Á Đông có lớp trung bì nhiều sắc tố và phản ứng viêm rất nhạy cảm. Đừng sao chép nồng độ acid treatment của phương Tây nếu bạn không muốn đối mặt với cơn ác mộng tăng sắc tố sau viêm (PIH).", "speaker": "BS. CKII Nguyễn Lan Anh"}', '["AHA", "BHA", "Niacinamide", "Trị mụn", "Lỗ chân lông", "Dược mỹ phẩm"]', 'Trong hơn một thập kỷ qua, sự bùng nổ của trào lưu Acid Treatment và các hoạt chất nồng độ cao đã tạo nên một cuộc cách mạng trong nhận thức làm đẹp. Tuy nhiên, sự thiếu hiểu biết về dược lý học và xu hướng lạm dụng nồng độ ''càng cao càng tốt'' đã đẩy hàng nghìn người vào tình trạng teo da, bỏng hóa chất và bùng phát mụn viêm mất kiểm soát. Việc nắm vững cấu trúc hóa học và đích tác động sinh học là chìa khóa then chốt để khai phóng toàn bộ sức mạnh của bộ ba hoạt chất kinh điển này.', 'Một chu trình dưỡng da thành công không phụ thuộc vào giá tiền của sản phẩm, mà nằm ở sự thấu hiểu dược học và khả năng kết hợp nhịp nhàng giữa các hoạt chất. Bằng cách luân phiên sử dụng BHA/AHA để làm sạch sâu và Niacinamide để củng cố tái tạo, bạn sẽ kiến tạo nên một cấu trúc da vững bền và rạng ngời.', '[{"name": "Dung Dịch Tẩy Tế Bào Chết BHA 2% Salicylic Acid Sạch Sâu", "category": "Dược Liệu Tẩy Da Chết", "price": 480000}, {"name": "Tinh Chất Niacinamide 5% Phục Hồi Thu Nhỏ Lỗ Chân Lông", "category": "Serum Cân Bằng", "price": 460000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('skin-barrier-recovery-14-days', 'Phác đồ cấp cứu da tổn thương và nhiễm corticoid trong 14 ngày: Liệu pháp phục hồi sinh học bằng Centella Asiatica và Panthenol', 'Đối mặt với tình trạng da đỏ rát, lộ mao mạch và ngứa châm chích sau khi dùng kem trộn hoặc peel da hỏng? Bác sĩ da liễu hướng dẫn lộ trình 3 giai đoạn tái thiết cấu trúc biểu mô.', 'treatment', 'dr_lan_anh', '08/09/2026', '16:00', '8 phút đọc', 4540, 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1400&q=85&auto=format&fit=crop', 'Khoa Lâm sàng Điều trị Biến chứng Thẩm mỹ Hoàng Bảo', 'Quy trình giải độc da, phác đồ cai nghiện corticoid khoa học, kết hợp hoạt chất Madecassoside phân lập tinh khiết và Vitamin B5 phân tử lượng siêu nhỏ.', '{"quote": "Khi lớp biểu bì bị bào mòn mất khả năng tự vệ, việc nhồi nhét kem dưỡng đậm đặc chỉ làm gia tăng gánh nặng trao đổi chất. Điều làn da cần nhất lúc này là sự tĩnh lặng sinh học và môi trường vô trùng để tái tạo.", "speaker": "BS. CKII Nguyễn Lan Anh"}', '["Corticoid", "Phục hồi màng ẩm", "B5 Panthenol", "Rau má", "Viêm da tiếp xúc"]', 'Tình trạng lạm dụng mỹ phẩm không rõ nguồn gốc chứa dẫn xuất Corticosteroid hoặc lạm dụng phương pháp lột tẩy bằng rượu thuốc, acid nồng độ cao đang là nguyên nhân hàng đầu khiến hàng nghìn phụ nữ rơi vào hội chứng suy giảm hàng rào bảo vệ da trầm trọng. Khi corticoid ức chế hệ miễn dịch cục bộ, mạch máu dưới da bị giãn nở cực độ tạo nên hiện tượng đỏ bừng, teo mô liên kết và mụn mủ bùng phát liên miên.', 'Hàng rào biểu bì của cơ thể sở hữu năng lực tự chữa lành phi thường nếu bạn thấu hiểu cơ chế và trao cho nó thời gian cùng các dưỡng chất tương thích sinh học. Đừng bao giờ đánh đổi sự trắng nhanh tức thời lấy sức khỏe lâu dài của làn da.', '[{"name": "Kem Dưỡng B5 Phục Hồi Chuyên Sâu Hoàng Bảo Cica-Care", "category": "Trị Liệu Phục Hồi", "price": 390000}, {"name": "Xịt Khoáng Tinh Khiết Cấp Cứu Da Tổn Thương Dị Ứng", "category": "Khoáng Y Tế", "price": 260000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('choose-lipstick-by-undertone', 'Nghệ thuật giải mã Undertone da: Phương pháp xác định sắc độ ngầm và cẩm nang lựa chọn sắc son nâng tầm thần thái', 'Tại sao cùng một thỏi son đỏ lại biến người này thành nữ hoàng bữa tiệc nhưng khiến người khác trông mệt mỏi và vàng răng? Chuyên gia trang điểm hướng dẫn trắc nghiệm sắc độ chuẩn xác.', 'makeup', 'hoang_nam', '05/09/2026', '11:20', '6 phút đọc', 3860, 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=1400&q=85&auto=format&fit=crop', 'Hoàng Nam Makeup Academy / Studio Nghệ thuật', 'Phân biệt Skintone và Undertone theo hệ thống bảng màu Munsell, kỹ thuật test tĩnh mạch và cách ứng dụng màu tương phản để tôn vinh nụ cười rạng rỡ.', '{"quote": "Son môi không đơn thuần là một món mỹ phẩm điểm tô màu mè. Đó là chữ ký thị giác đầu tiên thể hiện bản lĩnh, cảm xúc và khí chất riêng biệt của người phụ nữ.", "speaker": "Chuyên gia Hoàng Nam (Giám đốc Nghệ thuật Trang điểm)"}', '["Son môi", "Undertone", "Sắc tố da", "Bí quyết Makeup", "Trang điểm cá nhân"]', 'Trong giới trang điểm chuyên nghiệp quốc tế, có một câu nói kinh điển: ''Không có thỏi son xấu, chỉ có thỏi son đặt sai sắc tố da''. Rất nhiều phụ nữ chi tiêu hàng triệu đồng để sưu tầm các bộ sưu tập son phiên bản giới hạn, nhưng khi thoa lên mặt mộc lại cảm thấy khuôn mặt bị già đi hoặc tái nhợt. Căn nguyên của vấn đề nằm ở sự xung đột giữa quang phổ màu son và sắc tố ngầm dưới da (Undertone).', 'Hiểu rõ sắc tố của bản thân là bước khai mở đầu tiên trên con đường làm chủ nghệ thuật trang điểm. Khi màu son hòa nhịp cùng năng lượng tự nhiên của làn da, nụ cười của bạn sẽ tỏa sáng với trọn vẹn vẻ kiêu sa và cuốn hút.', '[{"name": "Son Kem Lì Nhung Mịn Dưỡng Ẩm Hoàng Bảo Velvet Lip Tint", "category": "Son Môi Cao Cấp", "price": 290000}, {"name": "Chì Định Hình Viền Môi Chống Trôi Sắc Nét", "category": "Trang Điểm Môi", "price": 180000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);
INSERT INTO `articles` (`id_article`, `title`, `subtitle`, `id_category`, `id_author`, `published_date`, `time_published`, `read_time`, `views`, `thumbnail`, `photo_credit`, `summary`, `pull_quote`, `tags`, `content_intro`, `content_conclusion`, `recommended_products`) VALUES ('clean-beauty-trend-2026', 'Làn sóng Clean Beauty 2026: Tương lai của mỹ phẩm thuần chay sinh học và trách nhiệm sinh thái toàn cầu', 'Tại sao các tập đoàn mỹ phẩm xa xỉ đang ráo riết tái cấu trúc chuỗi cung ứng theo tiêu chuẩn thuần chay và bao bì phân hủy sinh học? Phóng sự độc quyền về xu hướng tiêu dùng tỉnh thức.', 'trends', 'mai_phuong', '01/09/2026', '15:30', '7 phút đọc', 5120, 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1400&q=85&auto=format&fit=crop', 'Reuters / Diễn đàn Mỹ phẩm Sinh học Bền vững Quốc tế', 'Khảo sát sự dịch chuyển thói quen tiêu dùng của thế hệ Gen Z và Millennials đối với tiêu chuẩn Cruelty-Free, canh tác nông nghiệp tái sinh và chứng nhận Eco-friendly.', '{"quote": "Làm đẹp đích thực trong kỷ nguyên mới không thể xây dựng trên sự tổn hại của muôn loài hay rác thải nhựa đại dương. Một sản phẩm chân chính phải đẹp từ công thức đến đạo đức sản xuất.", "speaker": "Nhà báo Mai Phương (Ban Xu hướng & Môi trường sống)"}', '["Clean Beauty", "Mỹ phẩm thuần chay", "Bền vững", "Vegan", "Môi trường sống"]', 'Tại Tuần lễ Mỹ phẩm Bền vững Quốc tế diễn ra vào đầu năm 2026, hơn 82% các nhà phân phối và bán lẻ mỹ phẩm cao cấp xác nhận rằng tiêu chí ''Thuần chay'' (Vegan) và ''Bảo vệ động vật'' (Cruelty-Free) đã vươn lên thành yếu tố quyết định hàng đầu trong hành vi mua sắm của thế hệ trẻ. Khái niệm Clean Beauty đã vượt thoát khỏi ranh giới của một xu hướng tiếp thị nhất thời để trở thành một bộ quy chuẩn đạo đức sống còn đối với toàn bộ ngành công nghiệp tỷ đô.', 'Khi chúng ta đưa ra quyết định lựa chọn một chai mỹ phẩm xanh, đó không chỉ là sự chăm chút cho diện mạo cá nhân, mà là một lá phiếu ủng hộ một tương lai nhân đạo, bền vững và tràn đầy lòng trắc ẩn đối với hành tinh này.', '[{"name": "Sữa Rửa Mặt Hữu Cơ Bọt Mịn Chiết Xuất Tràm Trà Sinh Học", "category": "Mỹ Phẩm Xanh", "price": 280000}, {"name": "Nước Hoa Hồng Cân Bằng Cấp Ẩm Chuyên Sâu Hoàng Bảo", "category": "Thuần Chay", "price": 350000}]') ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- 4. INSERT INGREDIENT GUIDES
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('AHA (Glycolic / Lactic Acid)', 'Alpha Hydroxy Acid', 'Tẩy tế bào chết bề mặt, kích thích tăng sinh chu kỳ biểu bì, làm sáng các vết thâm nắng và đốm nâu li ti.', 'Da sần sùi, da thô ráp, da khô mất nước, da có nếp nhăn li ti', 'Nên dùng buổi tối, bắt buộc bôi kem chống nắng SPF 50+ phổ rộng ban ngày.', 'Nồng độ 5% - 7% cho người mới bắt đầu');
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('BHA (Salicylic Acid)', 'Beta Hydroxy Acid (2-Hydroxybenzoic acid)', 'Tan trong dầu, thâm nhập sâu vào nang lông, hóa lỏng bã nhờn, tiêu sừng và diệt khuẩn mụn kỵ khí.', 'Da dầu nhờn, da mụn ẩn, mụn đầu đen, bít tắc nang lông, lỗ chân lông to', 'Bắt đầu từ nồng độ 1-2%, dùng 2-3 lần/tuần để tránh hiện tượng khô căng cục bộ.', 'Nồng độ 1% - 2% chuẩn da liễu');
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('Hyaluronic Acid (HA)', 'Sodium Hyaluronate đa phân tử', 'Ngậm nước gấp 1000 lần trọng lượng phân tử, giữ ẩm đa tầng từ màng đáy đến bề mặt, tạo độ căng bóng sinh học.', 'Mọi loại da, đặc biệt là da dầu thiếu nước, da khô rát, da sau điều trị laser', 'Thoa trên nền da còn ẩm để tránh hiện tượng thẩm thấu ngược (hút ẩm ngược từ da ra không khí).', 'Dùng hàng ngày 2 lần sáng & tối');
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('Niacinamide (Vitamin B3)', 'Nicotinamide / 3-Pyridinecarboxamide', 'Thu nhỏ lỗ chân lông, điều tiết bã nhờn, kích thích tổng hợp Ceramide tự thân, ức chế vận chuyển sắc tố Melanin.', 'Da dầu mụn, da thâm sau mụn, da xỉn màu, da tổn thương hàng rào lipid', 'Rất lành tính, hoạt động ở pH trung tính 6.0, kết hợp tốt với B5 và Peptides.', 'Nồng độ tối ưu 2% - 5%');
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('Retinol & Bakuchiol', 'Vitamin A derivative & Phyto-Retinol', 'Tăng sinh Collagen type I và III, làm mờ nếp nhăn sâu, tăng tốc chu kỳ thay mới tế bào, ngăn ngừa lão hóa sớm.', 'Da bắt đầu lão hóa từ tuổi 22+, da có đốm đồi mồi, da dày sừng', 'Cần cấp ẩm kỹ bằng B5/Ceramide, bắt đầu từ nồng độ thấp đến cao, dùng cách ngày.', 'Nồng độ khởi đầu 0.1% - 0.3%');
INSERT INTO `ingredient_guides` (`name`, `scientific_name`, `role`, `suitable_for`, `note`, `dosage`) VALUES ('Centella Asiatica & B5', 'Madecassoside & D-Panthenol', 'Làm dịu phản ứng viêm cấp tính, hạ nhiệt làn da bỏng rát, sửa chữa cấu trúc mô liên kết và phục hồi mao mạch.', 'Da nhạy cảm, da sau peel, da tổn thương do kem trộn hoặc corticoid', 'Có thể thoa dặm nhiều lần trong ngày khi thấy da bị căng rát, không gây bí bách nang lông.', 'Dùng tự do theo nhu cầu phục hồi');

-- 4.5. ENSURE ROLES
INSERT IGNORE INTO `roles` (`id_role`, `name_role`) VALUES (1, 'ADMIN'), (2, 'WAREHOUSE_MANAGER'), (3, 'STAFF'), (4, 'CUSTOMER'), (5, 'ONLINE_STAFF');

-- 5. INSERT USERS
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (1, 'admin', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Hoàng Bảo (Quản Trị Viên)', 'admin@hoangbaocosmetics.vn', '0901234567', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (2, 'kho_hoangbao', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Trần Quốc Bảo (Quản Lý Kho)', 'kho@hoangbaocosmetics.vn', '0902345678', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (3, 'staff_linh', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Lê Thùy Linh (Nhân Viên Thu Ngân)', 'thuylinh@hoangbaocosmetics.vn', '0903456789', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (4, 'staff_hung', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Phạm Quang Hưng (Nhân Viên Tư Vấn)', 'quanghung@hoangbaocosmetics.vn', '0904567890', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (13, 'staff_online', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Nguyễn Mai Phương (Vận Hành Web & Content)', 'online@hoangbaocosmetics.vn', '0905678901', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (5, 'khach_an', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Nguyễn Văn An', 'nguyenvanan@gmail.com', '0912345671', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (6, 'khach_mai', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Trần Thị Mai', 'tranmai88@gmail.com', '0912345672', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (7, 'khach_huong', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Phạm Thu Hương', 'thuhuong.pt@gmail.com', '0912345673', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (8, 'khach_tri', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Đỗ Minh Trí', 'minhtri.do@gmail.com', '0912345674', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (9, 'khach_ngoc', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Vũ Bích Ngọc', 'bichngoc.vu@gmail.com', '0912345675', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (10, 'khach_thao', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Đặng Phương Thảo', 'phuongthao.dang@gmail.com', '0912345676', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (11, 'khach_tuan', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Lê Minh Tuấn', 'tuan.le@gmail.com', '0912345677', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);
INSERT INTO `users` (`id_user`, `username`, `password`, `full_name`, `email`, `phone_number`, `avatar`, `enabled`) VALUES (12, 'khach_lan', '$2a$10$W2XSm23owar28SmCyqABYuGh1fMDqj/OgcA.daZEdO/Fb/LyXgUpu', 'Hoàng Hương Lan', 'huonglan.hoang@gmail.com', '0912345678', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', b'1') ON DUPLICATE KEY UPDATE `full_name`=VALUES(`full_name`);

-- 6. INSERT USER_ROLES
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (1, 1);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (2, 2);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (3, 3);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (4, 3);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (13, 5);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (5, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (6, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (7, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (8, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (9, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (10, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (11, 4);
INSERT IGNORE INTO `user_roles` (`id_user`, `id_role`) VALUES (12, 4);

-- 7. INSERT SUPPLIERS
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (1, 'Công ty TNHH L''Oréal Việt Nam', '02839103000', 'Tầng 10, Tòa nhà Vincom Center, 72 Lê Thánh Tôn, P. Bến Nghé, Quận 1, TP. Hồ Chí Minh') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (2, 'Công ty Cổ phần Mỹ phẩm Cocoon Việt Nam', '02838328228', '14D1 Đường Thảo Điền, Thảo Điền, TP. Thủ Đức, TP. Hồ Chí Minh') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (3, 'Công ty TNHH DKSH Việt Nam', '02838125848', 'Tòa nhà Viettel, 285 Cách Mạng Tháng Tám, Phường 12, Quận 10, TP. Hồ Chí Minh') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (4, 'Công ty TNHH Amorepacific Việt Nam', '02838246232', 'Lầu 4A, Vincom Center, 72 Lê Thánh Tôn, P. Bến Nghé, Quận 1, TP. Hồ Chí Minh') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (5, 'Công ty TNHH Rohto-Mentholatum Việt Nam', '02743743631', 'Số 16 VSIP, Đường số 5, KCN Việt Nam - Singapore, Thuận An, Bình Dương') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `suppliers` (`id_supplier`, `name`, `phone`, `address`) VALUES (6, 'Công ty TNHH Quốc tế Unilever Việt Nam', '02854135686', 'A2-3 Khu đô thị mới Phú Mỹ Hưng, Tân Phong, Quận 7, TP. Hồ Chí Minh') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- 8. INSERT IMPORT RECEIPTS, DETAILS & INVENTORY LOGS
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (1, 1, 2, '2026-08-01 09:30:00', 73000000, 'Nhập lô hàng chống nắng và kem dưỡng phục hồi La Roche-Posay đầu tháng 8') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (1, 3, 100, 210000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (3, 2, 'IMPORT', 100, 1, '2026-08-01 09:30:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (1, 5, 120, 280000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (5, 2, 'IMPORT', 120, 1, '2026-08-01 09:30:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (1, 8, 80, 230000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (8, 2, 'IMPORT', 80, 1, '2026-08-01 09:30:00');
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (2, 2, 2, '2026-08-10 14:00:00', 58500000, 'Nhập bổ sung nước tẩy trang bí đao và tẩy da chết cà phê Đắk Lắk Cocoon') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (2, 12, 150, 170000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (12, 2, 'IMPORT', 150, 2, '2026-08-10 14:00:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (2, 80, 200, 75000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (80, 2, 'IMPORT', 200, 2, '2026-08-10 14:00:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (2, 25, 100, 180000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (25, 2, 'IMPORT', 100, 2, '2026-08-10 14:00:00');
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (3, 3, 2, '2026-08-20 10:15:00', 87600000, 'Nhập dược mỹ phẩm Bioderma và Paula''s Choice chính ngạch') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (3, 11, 120, 260000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (11, 2, 'IMPORT', 120, 3, '2026-08-20 10:15:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (3, 18, 60, 580000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (18, 2, 'IMPORT', 60, 3, '2026-08-20 10:15:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (3, 4, 90, 240000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (4, 2, 'IMPORT', 90, 3, '2026-08-20 10:15:00');
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (4, 4, 2, '2026-09-01 11:00:00', 88200000, 'Nhập mặt nạ ngủ môi Laneige và bộ sản phẩm Innisfree Trà Xanh') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (4, 65, 150, 280000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (65, 2, 'IMPORT', 150, 4, '2026-09-01 11:00:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (4, 30, 100, 310000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (30, 2, 'IMPORT', 100, 4, '2026-09-01 11:00:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (4, 70, 80, 190000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (70, 2, 'IMPORT', 80, 4, '2026-09-01 11:00:00');
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (5, 6, 2, '2026-09-10 15:30:00', 45000000, 'Nhập sản phẩm chăm sóc tóc Dove & TRESemmé chuyên sâu') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (5, 115, 100, 140000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (115, 2, 'IMPORT', 100, 5, '2026-09-10 15:30:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (5, 116, 100, 145000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (116, 2, 'IMPORT', 100, 5, '2026-09-10 15:30:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (5, 85, 150, 110000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (85, 2, 'IMPORT', 150, 5, '2026-09-10 15:30:00');
INSERT INTO `import_receipts` (`id_receipt`, `id_supplier`, `id_warehouse_manager`, `import_date`, `total_cost`, `note`) VALUES (6, 1, 2, '2026-09-18 16:45:00', 70400000, 'Nhập son môi 3CE và phấn mắt chuẩn bị đợt khuyến mãi thu đông') ON DUPLICATE KEY UPDATE `total_cost`=VALUES(`total_cost`);
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (6, 95, 100, 230000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (95, 2, 'IMPORT', 100, 6, '2026-09-18 16:45:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (6, 97, 120, 220000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (97, 2, 'IMPORT', 120, 6, '2026-09-18 16:45:00');
INSERT INTO `import_receipt_details` (`id_receipt`, `id_variant`, `quantity`, `import_price`) VALUES (6, 99, 100, 210000) ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (99, 2, 'IMPORT', 100, 6, '2026-09-18 16:45:00');

-- 9. INSERT ORDERS, ORDER DETAILS & REVIEWS
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (1, 'HBC-26090101', 5, NULL, 'ONLINE', 'Nguyễn Văn An', '0912345671', 'Số 45 Đường Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 705000, 0, 705000, 'VNPAY', 'VNP14829384', 'SUCCESS', 'DELIVERED', 'Giao giờ hành chính, gọi trước khi giao', '2026-09-02 10:15:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (1, 1, 1, 1, 385000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (1, 5, 1, 5.0, 'Chất kem đặc mịn, bôi lên da ẩm mượt ngay lập tức, cực kỳ thích hợp cho da khô mùa lạnh hoặc ngồi máy lạnh nhiều. Sẽ tiếp tục ủng hộ shop!', '2026-09-02 10:15:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (1, 3, 'EXPORT_SALE', -1, 1, '2026-09-02 10:15:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (2, 1, 3, 1, 320000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (3, 5, 2, 5.0, 'Kem dưỡng phục hồi B5+ chân ái của mình mỗi khi nặn mụn xong. Giảm đỏ rát rất rõ rệt chỉ sau 1 đêm. 10/10!', '2026-09-02 10:15:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (3, 3, 'EXPORT_SALE', -1, 1, '2026-09-02 10:15:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (2, 'HBC-26090202', 6, NULL, 'ONLINE', 'Trần Thị Mai', '0912345672', 'Số 12 Ngõ 88 Phố Huế, Phường Hàng Bài, Quận Hoàn Kiếm, Hà Nội', 630000, 0, 630000, 'MOMO', 'MOMO92837461', 'SUCCESS', 'DELIVERED', 'Giao tận tay bảo vệ chung cư nếu không gọi được', '2026-09-03 14:20:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (3, 2, 11, 1, 380000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (11, 6, 3, 5.0, 'Tẩy trang Bioderma hồng dùng siêu êm, làm sạch sâu bụi bẩn và kem chống nắng mà không hề bị khô căng rát mắt. Chai to dùng siêu tiết kiệm.', '2026-09-03 14:20:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (11, 3, 'EXPORT_SALE', -1, 2, '2026-09-03 14:20:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (4, 2, 80, 2, 125000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (80, 6, 4, 5.0, 'Mùi cà phê thơm nức mũi như đang ở quán cafe vậy, hạt scrub mịn không gây xước rát da, tắm xong da mềm mướt cực kỳ!', '2026-09-03 14:20:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (80, 3, 'EXPORT_SALE', -2, 2, '2026-09-03 14:20:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (3, 'HBC-26090303', 7, NULL, 'ONLINE', 'Phạm Thu Hương', '0912345673', 'Số 234 Nguyễn Tri Phương, Phường 4, Quận 10, TP. Hồ Chí Minh', 1200000, 0, 1200000, 'COD', NULL, NULL, 'DELIVERED', 'Khách thanh toán tiền mặt khi nhận hàng', '2026-09-05 09:00:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (5, 3, 18, 1, 850000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (18, 7, 5, 4.5, 'Hiệu quả đẩy mụn ẩn và kiềm dầu rất tốt. Lúc mới dùng hơi châm chích nhẹ nhưng sau 2 tuần da mịn màng hơn hẳn, mụn đầu đen ở cánh mũi giảm rõ rệt.', '2026-09-05 09:00:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (18, 3, 'EXPORT_SALE', -1, 3, '2026-09-05 09:00:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (6, 3, 2, 1, 350000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (2, 7, 6, 5.0, 'Sữa dưỡng ẩm CeraVe dùng rất nhẹ mặt, thấm nhanh không bị bết dính. Hàng chính hãng có tem phụ tiếng Việt đầy đủ.', '2026-09-05 09:00:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (2, 3, 'EXPORT_SALE', -1, 3, '2026-09-05 09:00:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (4, 'HBC-26090404', 8, NULL, 'ONLINE', 'Đỗ Minh Trí', '0912345674', 'Tầng 5 Tòa nhà Landmark 81, 720A Điện Biên Phủ, Phường 22, Bình Thạnh, TP. Hồ Chí Minh', 700000, 0, 700000, 'VNPAY', 'VNP14829440', 'SUCCESS', 'DELIVERED', 'Giao cho lễ tân tòa nhà', '2026-09-08 16:30:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (7, 4, 97, 1, 340000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (97, 8, 7, 5.0, 'Màu son lên môi cực xinh, mịn lì như nhung và không bị khô môi. Ăn uống nhẹ vẫn giữ được lớp base màu rất tự nhiên.', '2026-09-08 16:30:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (97, 3, 'EXPORT_SALE', -1, 4, '2026-09-08 16:30:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (8, 4, 95, 1, 360000, b'1') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `reviews` (`id_product`, `id_user`, `id_order_detail`, `rating_point`, `content`, `created_at`) VALUES (95, 8, 8, 4.5, 'Phấn má 3CE màu tự nhiên, bám màu lâu tầm 6-7 tiếng, hộp nhỏ gọn dễ mang đi chơi.', '2026-09-08 16:30:00');
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (95, 3, 'EXPORT_SALE', -1, 4, '2026-09-08 16:30:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (5, 'HBC-26090505', NULL, 3, 'OFFLINE', 'Lê Thị Hà (Khách Vãng Lai)', '0987654321', 'Mua trực tiếp tại Showroom Hoàng Bảo Cosmetics - 120 Hai Bà Trưng, Quận 1', 695000, 0, 695000, 'CASH', NULL, NULL, 'DELIVERED', 'Khách mua tại quầy - Thu ngân Thùy Linh thanh toán', '2026-09-10 11:10:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (9, 5, 12, 1, 275000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (12, 3, 'EXPORT_SALE', -1, 5, '2026-09-10 11:10:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (10, 5, 65, 1, 420000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (65, 3, 'EXPORT_SALE', -1, 5, '2026-09-10 11:10:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (6, 'HBC-26090606', 9, NULL, 'ONLINE', 'Vũ Bích Ngọc', '0912345675', 'Số 78 Trần Phú, Phường Hải Châu 1, Quận Hải Châu, TP. Đà Nẵng', 900000, 0, 900000, 'VNPAY', 'VNP14829555', 'SUCCESS', 'DELIVERED', 'Đóng gói bọc xốp cẩn thận giúp em', '2026-09-12 13:40:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (11, 6, 5, 1, 420000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (5, 3, 'EXPORT_SALE', -1, 6, '2026-09-12 13:40:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (12, 6, 30, 1, 480000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (30, 3, 'EXPORT_SALE', -1, 6, '2026-09-12 13:40:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (7, 'HBC-26090707', 10, NULL, 'ONLINE', 'Đặng Phương Thảo', '0912345676', 'Số 15 Phố Cầu Đất, Phường Cầu Đất, Quận Ngô Quyền, TP. Hải Phòng', 640000, 0, 640000, 'MOMO', 'MOMO92839912', 'SUCCESS', 'DELIVERED', 'Khách dặn giao buổi sáng', '2026-09-14 20:05:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (13, 7, 8, 1, 350000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (8, 3, 'EXPORT_SALE', -1, 7, '2026-09-14 20:05:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (14, 7, 70, 1, 290000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (70, 3, 'EXPORT_SALE', -1, 7, '2026-09-14 20:05:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (8, 'HBC-26090808', NULL, 4, 'OFFLINE', 'Hoàng Ngọc Ánh (Khách Vãng Lai)', '0978123456', 'Mua trực tiếp tại Showroom Hoàng Bảo Cosmetics - 120 Hai Bà Trưng, Quận 1', 445000, 0, 445000, 'MOMO', 'MOMO_POS_7721', 'SUCCESS', 'DELIVERED', 'Khách quét QR MoMo tại quầy', '2026-09-15 15:20:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (15, 8, 99, 1, 320000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (99, 4, 'EXPORT_SALE', -1, 8, '2026-09-15 15:20:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (16, 8, 80, 1, 125000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (80, 4, 'EXPORT_SALE', -1, 8, '2026-09-15 15:20:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (9, 'HBC-26090909', 11, NULL, 'ONLINE', 'Lê Minh Tuấn', '0912345677', 'Số 56 Đường 30/4, Phường An Phú, Quận Ninh Kiều, Cần Thơ', 425000, 30000, 455000, 'COD', NULL, NULL, 'SHIPPING', 'Đang vận chuyển qua GHTK (Mã vận đơn: GHTK882910)', '2026-09-19 10:00:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (17, 9, 115, 1, 210000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (115, 3, 'EXPORT_SALE', -1, 9, '2026-09-19 10:00:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (18, 9, 116, 1, 215000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (116, 3, 'EXPORT_SALE', -1, 9, '2026-09-19 10:00:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (10, 'HBC-26091010', 12, NULL, 'ONLINE', 'Hoàng Hương Lan', '0912345678', 'Biệt thự B2 KĐT Ciputra, Phường Xuân La, Quận Tây Hồ, Hà Nội', 1270000, 0, 1270000, 'VNPAY', 'VNP14830122', 'SUCCESS', 'SHIPPING', 'Đang giao ViettelPost', '2026-09-19 18:30:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (19, 10, 18, 1, 850000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (18, 3, 'EXPORT_SALE', -1, 10, '2026-09-19 18:30:00');
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (20, 10, 65, 1, 420000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (65, 3, 'EXPORT_SALE', -1, 10, '2026-09-19 18:30:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (11, 'HBC-26091111', 5, NULL, 'ONLINE', 'Nguyễn Văn An', '0912345671', 'Số 45 Đường Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh', 295000, 30000, 325000, 'COD', NULL, NULL, 'PROCESSING', 'Đã xác nhận đơn qua điện thoại, đang soạn hàng đóng gói', '2026-09-21 08:45:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (21, 11, 25, 1, 295000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (25, 3, 'EXPORT_SALE', -1, 11, '2026-09-21 08:45:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (12, 'HBC-26091212', 6, NULL, 'ONLINE', 'Trần Thị Mai', '0912345672', 'Số 12 Ngõ 88 Phố Huế, Phường Hàng Bài, Quận Hoàn Kiếm, Hà Nội', 330000, 30000, 360000, 'MOMO', 'MOMO92841029', 'PENDING', 'PROCESSING', 'Đã thanh toán MoMo thành công, nhân viên đang lấy hàng từ kệ', '2026-09-21 14:10:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (22, 12, 85, 2, 165000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `inventory_logs` (`id_variant`, `id_user`, `transaction_type`, `quantity_change`, `reference_id`, `created_at`) VALUES (85, 3, 'EXPORT_SALE', -2, 12, '2026-09-21 14:10:00');
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (13, 'HBC-26091313', 7, NULL, 'ONLINE', 'Phạm Thu Hương', '0912345673', 'Số 234 Nguyễn Tri Phương, Phường 4, Quận 10, TP. Hồ Chí Minh', 660000, 0, 660000, 'COD', NULL, NULL, 'PENDING', 'Đơn hàng mới tạo trên website, chờ gọi xác nhận', '2026-09-22 09:15:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (23, 13, 1, 1, 385000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (24, 13, 12, 1, 275000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (14, 'HBC-26091414', 8, NULL, 'ONLINE', 'Đỗ Minh Trí', '0912345674', 'Tầng 5 Tòa nhà Landmark 81, 720A Điện Biên Phủ, Phường 22, Bình Thạnh, TP. Hồ Chí Minh', 850000, 0, 850000, 'COD', NULL, NULL, 'CANCELLED', 'Khách yêu cầu hủy do đặt nhầm dung tích sản phẩm', '2026-09-16 11:25:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (25, 14, 18, 1, 850000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);
INSERT INTO `orders` (`id_order`, `order_code`, `id_user`, `id_staff`, `order_type`, `customer_name`, `phone_number`, `delivery_address`, `total_product_price`, `shipping_fee`, `total_amount`, `payment_method`, `transaction_id`, `webhook_status`, `status`, `note`, `created_at`) VALUES (15, 'HBC-26091515', 9, NULL, 'ONLINE', 'Vũ Bích Ngọc', '0912345675', 'Số 78 Trần Phú, Phường Hải Châu 1, Quận Hải Châu, TP. Đà Nẵng', 420000, 30000, 450000, 'VNPAY', 'VNP14829801', 'FAILED', 'CANCELLED', 'Hủy tự động do quá thời gian chờ thanh toán VNPAY (15 phút)', '2026-09-17 17:50:00') ON DUPLICATE KEY UPDATE `order_code`=VALUES(`order_code`);
INSERT INTO `order_details` (`id_order_detail`, `id_order`, `id_variant`, `quantity`, `price`, `is_reviewed`) VALUES (26, 15, 5, 1, 420000, b'0') ON DUPLICATE KEY UPDATE `quantity`=VALUES(`quantity`);

-- 10. INSERT FAVORITE PRODUCTS
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (5, 1, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (5, 3, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (5, 5, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (5, 18, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (6, 11, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (6, 12, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (6, 80, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (6, 25, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (7, 2, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (7, 18, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (7, 65, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (7, 30, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (8, 95, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (8, 97, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (8, 99, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (9, 5, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (9, 30, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (9, 70, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (9, 11, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (10, 8, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (10, 70, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (10, 80, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (11, 115, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (11, 116, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (11, 85, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (12, 18, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (12, 65, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (12, 97, '2026-09-15 10:00:00');
INSERT IGNORE INTO `favorite_products` (`id_user`, `id_product`, `created_at`) VALUES (12, 1, '2026-09-15 10:00:00');

-- 11. INSERT FEEDBACKS
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `subject`, `message`, `is_read`, `created_at`) VALUES ('Trần Bảo Ngọc', 'baongoc.tran@gmail.com', '0938123456', 'Tư vấn phác đồ chăm sóc da dầu mụn ẩn', 'Chào Hoàng Bảo Cosmetics, da em thuộc loại da dầu nhiều, vùng chữ T bóng nhờn và đang bị mụn ẩn li ti ở trán và hai bên má. Em muốn nhờ shop tư vấn giúp em một chu trình làm sạch và phục hồi phù hợp với ngân sách sinh viên ạ. Em cảm ơn shop!', b'1', '2026-09-10 09:30:00');
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `subject`, `message`, `is_read`, `created_at`) VALUES ('Nguyễn Đức Thành', 'ducthanh.spa@gmail.com', '0918765432', 'Hỏi về chính sách đại lý & lấy sỉ mỹ phẩm chính hãng', 'Kính gửi Ban Quản Trị, bên mình hiện đang vận hành chuỗi spa tại Đà Nẵng và muốn tìm kiếm nguồn cung ứng ổn định cho các dòng dược mỹ phẩm La Roche-Posay, CeraVe và Bioderma. Rất mong nhận được thông tin chiết khấu và chính sách đại lý qua email.', b'1', '2026-09-12 14:15:00');
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `subject`, `message`, `is_read`, `created_at`) VALUES ('Lê Thúy Nga', 'thuynga.le@gmail.com', '0909112233', 'Thắc mắc về thời gian giao hàng tại Cần Thơ', 'Shop cho mình hỏi nếu mình đặt đơn hàng trị giá hơn 800k giao về quận Ninh Kiều, Cần Thơ thì khoảng bao lâu nhận được hàng ạ? Đơn hàng có được freeship và cho kiểm tra hàng trước khi thanh toán không shop?', b'0', '2026-09-18 16:40:00');
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `subject`, `message`, `is_read`, `created_at`) VALUES ('Võ Thị Thanh Thảo', 'thanhthao.vo@gmail.com', '0945678901', 'Khen ngợi dịch vụ đóng gói và quà tặng kèm', 'Mình vừa nhận được gói hàng trưa nay. Shop đóng gói cực kỳ chỉn chu, có túi bóng khí dày dặn, lại còn tặng kèm mẫu thử tinh chất B5 nữa. Nhân viên tư vấn nhiệt tình, sản phẩm dùng rất thích. Chắc chắn sẽ ủng hộ shop lâu dài!', b'1', '2026-09-19 11:20:00');
INSERT INTO `feedbacks` (`name`, `email`, `phone`, `subject`, `message`, `is_read`, `created_at`) VALUES ('Phạm Hoàng Nam', 'hoangnam.dev@gmail.com', '0988776655', 'Góp ý trải nghiệm thanh toán quét mã MoMo', 'Giao diện website của shop rất đẹp và mượt mà. Tuy nhiên ở bước thanh toán qua cổng MoMo QR, đôi lúc mã QR hiển thị hơi chậm một chút trên Safari di động. Shop kiểm tra tối ưu thêm nhé. Chúc shop ngày càng phát triển!', b'0', '2026-09-20 20:05:00');

SET FOREIGN_KEY_CHECKS = 1;
